[package]
name = "spandoc-toy"
version = "0.1.0"
authors = ["Benjamin Herr <ben@0x539.de>"]
edition = "2018"

[dependencies]
tracing = "0.1.8"
tracing-subscriber = "0.2"
tracing-error = "0.1"
spandoc = "0.1"
eyre = "0.1"
